export const BasePath = 'https://d28em8ghn6cnbn.cloudfront.net/website_images';

export const IMAGES: Record<string, string> = {
    ERROR: `${BasePath}/404.png` ,
    ERROR_PERSON: `${BasePath}/404-person.svg`,
    ABOUTUIMG1: `${BasePath}/aboutImg1.svg`,
    ABOUTUIMG2: `${BasePath}/aboutImg2.svg`,
    ABOUTUS1: `${BasePath}/aboutus1.jpeg`,
    ABOUTUS2: `${BasePath}/aboutus2.png`,
    ABOUTUS3: `${BasePath}/aboutus3.jpeg`,
    AC:`${BasePath}/ac.svg`,
    ACCORDARROW:`${BasePath}/accordarrow.svg`,
    ADULTS:`${BasePath}/adults.svg`,
    AMERICAN_EX:`${BasePath}/american-ex.svg`,
    APPLE_ICON: `${BasePath}/apple-icon.svg`,
    APPLE_STORE:`${BasePath}/apple-store.png`,
    APP_MOCKUP:`${BasePath}/app-mockup.png`,
    ARROW:`${BasePath}/arrow.svg`,
    ARROW_UP_RIGHT:`${BasePath}/arrow-up-right.svg`,
    BANNER_2:`${BasePath}/banner-2.jpg`,
    BANNER_QR:`${BasePath}/banner-Qr.png`,
    BARCODE:`${BasePath}/barcode.png`,
    BED:`${BasePath}/bed.svg`,
    BELL:`${BasePath}/bell.svg`,
    BLIND_PASSWORD:`${BasePath}/blind_password.svg`,
    BLOG1:`${BasePath}/blog1.jpeg`,
    BLOG4:`${BasePath}/blog4.jpeg`,
    BLOG5:`${BasePath}/blog5.jpeg`,
    BLOG_BG:`${BasePath}/blog-bg.png`,
    BLOG_DETAILS_BG:`${BasePath}/blog-details-bg.jfif`,
    BOOKING:`${BasePath}/booking.svg`,
    BOOKING_CONFIRM:`${BasePath}/booking-confirm.svg`,
    BOOKING_MANAGE:`${BasePath}/booking-manage.svg`,
    BOOST_YOUR_SUCCESS:`${BasePath}/boost-your-success.jpg`,
    BREAKFAST:`${BasePath}/breakfast.svg`,
    CALENDAR:`${BasePath}/calendar.svg`,
    CALL:`${BasePath}/call.svg`,
    CALL_WHITE:`${BasePath}/call-white.svg`,
    CAMERA:`${BasePath}/camera.svg`,
    CAMERA_RED:`${BasePath}/camera-red.svg`,
    CANCELLATION_POLICY:`${BasePath}/cancellation-policy.svg`,
    CARD:`${BasePath}/card.png`,
    C_EMAIL:`${BasePath}/c-email.svg`,
    CHART:`${BasePath}/chart.svg`,
    CHECKMARK:`${BasePath}/checkmark.svg`,
    CHECKMARK_GREEN:`${BasePath}/checkmark-green.svg`,
    CHECKMARK_RED:`${BasePath}/checkmark-red.svg`,
    C_MAPPING:`${BasePath}/c-mapping.svg`,
    CONFIRM_EMAIL:`${BasePath}/confirm-email.svg`,
    CONTACT_BG:`${BasePath}/contact-bg.jfif`,
    C_PHONE:`${BasePath}/c-phone.svg`,
    DATE_RANGE:`${BasePath}/date-range.svg`,
    DATE_RANGE_WHITE:`${BasePath}/date-range-white.svg`,
    DESTINATION1:`${BasePath}/destination1.jpeg`,
    DESTINATION2:`${BasePath}/destination2.jpeg`,
    DESTINATION3:`${BasePath}/destination3.jpeg`,
    DESTINATION4:`${BasePath}/destination4.jpeg`,
    DESTINATION5:`${BasePath}/destination5.jpeg`,
    DESTINATION6:`${BasePath}/destination6.jpeg`,
    DISCOUNT:`${BasePath}/discount.svg`,
    DISCOUNT_RED:`${BasePath}/discount-red.svg`,
    DISCOUNT_RIBBON:`${BasePath}/discount-ribbon.svg`,
    DL_INVOICE:`${BasePath}/dl-invoice.svg`,
    DOLLAR_SQUARE:`${BasePath}/dollar-square.svg`,
    DOWNLOAD_ICON:`${BasePath}/download-icon.svg`,
    DROPDOWN_AFTER:`${BasePath}/dropdown-after.svg`,
    EARNINGS:`${BasePath}/earnings.svg`,
    EDIT:`${BasePath}/edit.svg`,
    EDIT_BTN:`${BasePath}/edit-btn.svg`,
    EDIT_PENCIL:`${BasePath}/edit-pencil.svg`,
    EMAIL:`${BasePath}/email.svg`,
    EMAIL_VARIFIED:`${BasePath}/email-verified.svg`,
    EVENT:`${BasePath}/event.svg`,
    FACILITY:`${BasePath}/facility.svg`,
    FAQ_BG:`${BasePath}/faq-bg.jpeg`,
    FAVORITE:`${BasePath}/favotire.svg`,
    FAVORITE_WHITE:`${BasePath}/favotire-white.svg`,
    FB:`${BasePath}/fb.svg`,
    FB_ICON:`${BasePath}/fb-icon.svg`,
    FEEDBACK_REQUEST:`${BasePath}/feedback-request.svg`,
    FLEXIBLE_PRICING:`${BasePath}/flexible-pricing.svg`,
    FREEWIFI:`${BasePath}/freewifi.svg`,
    GIRL_USING_MOBILE:`${BasePath}/girl-using-mobile.png`,
    GOA:`${BasePath}/goa.jpg`,
    GOOGLE_DL:`${BasePath}/google-dl.svg`,
    GOOGLE_ICON:`${BasePath}/google-icon.svg`,
    GOOGLE_STORE:`${BasePath}/google-store.png`,
    GROW_WITH_US:`${BasePath}/grow-with-us.jpg`,
    GUARANTEE:`${BasePath}/guarantee.svg`,
    HAND:`${BasePath}/hand.svg`,
    HEART:`${BasePath}/heart.svg`,
    HEART_WHITE:`${BasePath}/heart-white.svg`,
    HOME:`${BasePath}/home.svg`,
    HOME_WHITE:`${BasePath}/home-white.svg`,
    HOST_AVATAR:`${BasePath}/host-avatar.svg`,
    HOST_BG:`${BasePath}/host-bg.jpeg`,
    HOTEL:`${BasePath}/hotel.png`,
    HOTEL_ICON:`${BasePath}/hotel-icon.svg`,
    HOTELSEARCH:`${BasePath}/hotelsearch.png`,
    HOUSE:`${BasePath}/house.svg`,
    HOUSEKEEPING:`${BasePath}/housekeeping.svg`,
    HYGIENEPLUS:`${BasePath}/hygieneplus.svg`,
    INSTA:`${BasePath}/insta.svg`,
    IPHONE_DL:`${BasePath}/iphone-dl.svg`,
    IPHONE_MOCKUP:`${BasePath}/iphone-mockup.svg`,
    JAIPUR:`${BasePath}/jaipur.jpg`,
    JAISALMER:`${BasePath}/jaisalmer.jpg`,
    JCB:`${BasePath}/jcb.svg`,
    LOCATION:`${BasePath}/location.png`,
    LOCATIONS:`${BasePath}/location.svg`,
    LOCATION_PIN:`${BasePath}/location-pin.svg`,
    LOCATION_SEARCH_PIN:`${BasePath}/location-search-pin.svg`,
    LOCK:`${BasePath}/lock.svg`,
    LOCPIN_GREY:`${BasePath}/locpin-grey.svg`,
    LOGIN_AVTAR_RED:`${BasePath}/login-avtar-red.svg`,
    LOGO: `${BasePath}/logo.png`,
    LOGO1: `${BasePath}/logo1.png`,
    LOGO2: `${BasePath}/logo2.png`,
    LOGO_WHITE: `${BasePath}/logo-white.png`,
    MANALI:`${BasePath}/manali.jpg`,
    MASTER_CARD:`${BasePath}/master-card.svg`,
    MENU:`${BasePath}/menu.png`,
    MINUS:`${BasePath}/minus.svg`,
    MISSION1:`${BasePath}/mission1.jpeg`,
    MISSION2:`${BasePath}/mission2.jpeg`,
    MISSION3:`${BasePath}/mission3.png`,
    MISSION4:`${BasePath}/mission4.jpeg`,
    MODAL_BG:`${BasePath}/MODAL-bg.jpg`,
    MUMBAI:`${BasePath}/mumbai.jpg`,
    NO_IMAGE:`${BasePath}/no-image.png`,
    NORECORD:`${BasePath}/norecord.svg`,
    NOT_FOUND_PAGE:`${BasePath}/not-found-page.svg`,
    NOT_VALIDATE:`${BasePath}/not-validate.svg`,
    OFFER_AVATAR1:`${BasePath}/offer-avatar1.png`,
    OFFER_AVATAR2:`${BasePath}/offer-avatar2.png`,
    OFFER_AVATAR3:`${BasePath}/offer-avatar3.png`,
    OUR_STORY1:`${BasePath}/our-story1.png`,
    OUR_STORY2:`${BasePath}/our-story2.png`,
    PAYPAL:`${BasePath}/paypal.svg`,
    PAYPAY_TEXT:`${BasePath}/paypal-text.svg`,
    PIN:`${BasePath}/pin.git`,
    PINS:`${BasePath}/pin.png`,
    PLAYSTORE_ICON:`${BasePath}/playstore-icon.svg`,
    PLUS:`${BasePath}/plus.svg`,
    POLICIES:`${BasePath}/policies.svg`,
    POWERBACKUP:`${BasePath}/powerbackup.svg`,
    PROFILE:`${BasePath}/profile.svg`,
    PROFILE_2USER:`${BasePath}/profile-2user.svg`,
    PROFILE_MANAGE:`${BasePath}/profile-manage.svg`,
    PROFILE_WHITE:`${BasePath}/profile-white.svg`,
    PUNJAB:`${BasePath}/punjab.jpg`,
    RED_BOX_SHADOW:`${BasePath}/red-box-shadow.svg`,
    RED_CALENDAR:`${BasePath}/red-calendar.svg`,
    REDIRECT_ARROW:`${BasePath}/redirect-arrow.svg`,
    REDIRECT_ARROW_WHITE:`${BasePath}/redirect-arrow-white.svg`,
    RED_LOGO:`${BasePath}/red-logo.png`,
    RED_X_MARK:`${BasePath}/red-x-mark.svg`,
    REVIEW_BLACK:`${BasePath}/review-black.svg`,
    RIGHT_ARROW:`${BasePath}/right-arrow.svg`,
    RIGHT_ARROW_RED:`${BasePath}/right-arrow-red.svg`,
    RIGHT_CIRCLE:`${BasePath}/right-circle.svg`,
    ROOM:`${BasePath}/room.svg`,
    ROOM_LIGHT:`${BasePath}/room-light.svg`,
    ROOM_MANAGE:`${BasePath}/room-manage.svg`,
    SEARCH_NORMAL:`${BasePath}/search-normal.svg`,
    SEARCH_RED:`${BasePath}/search-red.svg`,
    SEE_MAP:`${BasePath}/see-map.svg`,
    SHIELD_ICON:`${BasePath}/shield-icon.svg`,
    SIDEBAR_ICON:`${BasePath}/sidebar-icon.png`,
    STAR:`${BasePath}/star.svg`,
    SUPPORT:`${BasePath}/support.svg`,
    TAG:`${BasePath}/tag.svg`,
    TEAM1:`${BasePath}/team1.png`,
    TEAM2:`${BasePath}/team2.png`,
    TEAM3:`${BasePath}/team3.png`,
    TEAM4:`${BasePath}/team4.png`,
    TEAM5:`${BasePath}/team5.png`,
    TEAM_WORK:`${BasePath}/team-work.svg`,
    TESTIMONIAL_IMAGE01:`${BasePath}/testimonial-image01.png`,
    TESTIMONIAL_IMAGE02:`${BasePath}/testimonial-image02.png`,
    TESTIMONIAL_IMAGE03:`${BasePath}/testimonial-image03.png`,
    TESTIMONIAL_IMAGE04:`${BasePath}/testimonial-image04.png`,
    TWITTER:`${BasePath}/twitter.svg`,
    USER:`${BasePath}/user.svg`,
    VALID:`${BasePath}/valid.svg`,
    VERIFIED:`${BasePath}/verified.svg`,
    VIEWALL:`${BasePath}/viewall.svg`,
    VISA:`${BasePath}/visa.svg`,
    VISIBILITY:`${BasePath}/visibility.svg`,
    VISIBILITY_OFF:`${BasePath}/visibility_off.svg`,
    WALKING_MAN:`${BasePath}/walking-man.svg`,
    WALRM_WHITE_LOGO:`${BasePath}/walrm-white-logo.png`,
    WHATSAPP:`${BasePath}/whatsapp.png`,
    WIFI:`${BasePath}/wifi.svg`,
    YTUBE:`${BasePath}/ytube.svg`,














    
    
};